
---
output: 
  html_document:
  pdf_document: default
  word_document: default
title: "Assignment 9: Visualization - Revealing a graph"
---

***How to do it?***: 

- Open the Rmarkdown file of this assignment ([link](fa2021_assignment9.Rmd)) in Rstudio. 

- Right under each **question**, insert  a code chunk (you can use the hotkey `Ctrl + Alt + I` to add a code chunk) and code the solution for the question. 

- `Knit` the rmarkdown file (hotkey: `Ctrl + Alt + K`) to export an html.  

-  Publish the html file to your Githiub Page. 

***Submission***: Submit the link on Github of the assignment to Canvas

```{r setup, include=FALSE}
knitr::opts_chunk$set(message = FALSE)
```


-------

1. Use the dataset by of covid 19 by WHO at https://covid19.who.int/WHO-COVID-19-global-data.csv. Find the three countries with the most numbers of deaths by Covid-19. 

Hint: 

-  Use `filter` to select the most current date 

-  Pipe with `arrange(-Cumulative_deaths)` to rank the data by the number of cumulative deaths


2. Make a plot revealing the number of deaths in the three countries with the most numbers of deaths

3. Create the new variable (column) `death_per_cases` recording the number of deaths per cases (Hint: divide cumulative deaths by cumulative cases).  What are the three countries with the highest deaths per cases? 

4. Make a plot revealing the number of deaths per cases of the US, Italy and Mexico. 

5. Use `transition_reveal` to create three animated graph with the vaccination data at 

https://raw.githubusercontent.com/govex/COVID-19/master/data_tables/vaccine_data/us_data/time_series/vaccine_data_us_timeline.csv


